/* Run only after saving all evidence/results. */

BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE flex_oracle_perf_results PURGE';
EXCEPTION WHEN OTHERS THEN NULL;
END;
/

BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE flex_product_perf PURGE';
EXCEPTION WHEN OTHERS THEN NULL;
END;
/

BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE flex_oracle_results PURGE';
EXCEPTION WHEN OTHERS THEN NULL;
END;
/

BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE flex_products PURGE';
EXCEPTION WHEN OTHERS THEN NULL;
END;
/
